/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kelompok 7
 * S1SI
 * 07A
 */
public class MenuUtama extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lblKelompok = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        itemBarang = new javax.swing.JMenuItem();
        itemLokasi = new javax.swing.JMenuItem();
        itemUser = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        itemMasuk = new javax.swing.JMenuItem();
        itemKeluar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 527));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 527));

        lblKelompok.setBackground(new java.awt.Color(153, 255, 0));
        lblKelompok.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKelompok.setForeground(new java.awt.Color(255, 153, 0));
        lblKelompok.setText("Kelompok 7_S1 SI-07-A");

        lbl.setFont(new java.awt.Font("Segoe UI", 3, 80)); // NOI18N
        lbl.setText("Class Keeper");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKelompok)
                        .addGap(299, 299, 299))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addComponent(lblKelompok)
                .addGap(243, 243, 243))
        );

        menuBar.setBackground(new java.awt.Color(242, 242, 242));
        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuBar.setMargin(new java.awt.Insets(0, 10, 0, 10));
        menuBar.setPreferredSize(new java.awt.Dimension(70, 40));

        menuMaster.setText("Master");

        itemBarang.setText("Data Barang");
        itemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarangActionPerformed(evt);
            }
        });
        menuMaster.add(itemBarang);

        itemLokasi.setText("Data Lokasi");
        itemLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLokasiActionPerformed(evt);
            }
        });
        menuMaster.add(itemLokasi);

        itemUser.setText("Data User");
        itemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUserActionPerformed(evt);
            }
        });
        menuMaster.add(itemUser);

        menuBar.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        itemMasuk.setText("Inventaris Masuk");
        itemMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMasukActionPerformed(evt);
            }
        });
        menuTransaksi.add(itemMasuk);

        itemKeluar.setText("Inventaris Keluar");
        itemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKeluarActionPerformed(evt);
            }
        });
        menuTransaksi.add(itemKeluar);

        menuBar.add(menuTransaksi);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarangActionPerformed
        Barang frmB = new Barang();
        frmB.setVisible(true);
    }//GEN-LAST:event_itemBarangActionPerformed

    private void itemLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLokasiActionPerformed
        Lokasi frmL = new Lokasi();
        frmL.setVisible(true);
    }//GEN-LAST:event_itemLokasiActionPerformed

    private void itemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUserActionPerformed
        User frmU = new User();
        frmU.setVisible(true);
    }//GEN-LAST:event_itemUserActionPerformed

    private void itemMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMasukActionPerformed
        InventarisMasuk frmIM = new InventarisMasuk();
        frmIM.setVisible(true);
    }//GEN-LAST:event_itemMasukActionPerformed

    private void itemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKeluarActionPerformed
        InventarisKeluar frmIK = new InventarisKeluar();
        frmIK.setVisible(true);
    }//GEN-LAST:event_itemKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBarang;
    private javax.swing.JMenuItem itemKeluar;
    private javax.swing.JMenuItem itemLokasi;
    private javax.swing.JMenuItem itemMasuk;
    private javax.swing.JMenuItem itemUser;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblKelompok;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
